

name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        #uses: docker/login-action@v1
        #with:
        #  username: ${{ secrets.DOCKER_USERNAME }}
        #  password: ${{ secrets.DOCKER_TOKEN }}
          
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
    # Username to connect to Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
    # Password to connect to Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}
    # Docker build context
        context: 
    # Docker build file
        file: ./Dockerfile
    # Docker repository owner
        repoOwner: chore05
    # Docker repository
      #  repository: 
    # Docker image tag
        tag: techtrends:latest
    # Registry you want to push the Docker image
        registry: chore05/dockerfile_for_techtrends_application
      -
        name: Build and push
        id: chore05
        #uses: docker/build-push-action@v2
        uses: docker/build-push-action@v4.0.0
      # with:
      #   push: true
        
         with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          #registry: chore05/dockerfile_for_techtrends_application
         # tags: chore05/dockerfile_for_techtrends_application:techtrends:latest
          tags: chore05/dockerfile_for_techtrends_application :latest
          
        # tags: ${{ steps.meta_pytorch.outputs.tags }}
        # tags: ${{ chore05/dockerfile_for_techtrends_application }}
        # labels: ${{ techtrends }}:latest
        #tags : ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.repository }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
