name: Docker publish

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: https://hub.docker.com/repository/docker/chore05/dockerfile_for_techtrends_application
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push web
        id: chore05
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./web
          tags: chore05/dockerfile_for_techtrends_application/techtrend:latest
